### PR TITLE
New vault tokens location

### PR DESCRIPTION
**Pull request by eherot**

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
A few other touchpoints in other cookbooks for this, but otherwise, LGTM :shipit:

**Comment by eherot** [comment]
which ones besides `et_base`?

**Comment by jeffbyrnes** [comment]
Might be the only other one: https://github.com/evertrue/et_secrets-cookbook/blob/5330a513427a81f98a6eee93b9d58f57b7d18629/recipes/renew_vault_token.rb#L2

**Comment by eherot** [comment]
Oh I have a whole separate PR I'm working on with `et_secrets` to support this.

**Comment by jeffbyrnes** [comment]
Perfect!

**Pull request merged**
